name: NotBounties
version: '${project.version}'
main: me.jadenp.notbounties.NotBounties
api-version: 1.13
authors: [ Not_Jaden ]
description: kill...
folia-supported: true
softdepend:
  - PlaceholderAPI
  - HeadDataBase
  - Vault
  - LiteBans
  - SkinsRestorer
  - BetterTeams
  - Towny
  - Geyser-Spigot
  - floodgate
  - Kingdoms
  - Lands
  - WorldGuard
  - Factions
  - Essentials
  - MythicLib
  - Duels
  - SimpleClans
  - packetevents
  - Skript
commands:
  notbounties:
    description: Use all of the bounty commands.
  notbountiesadmin:
    description: Open the GUI for other people.
    aliases:
      - bountyadmin
permissions:
  notbounties.admin:
    default: op
    description: Remove or edit bounties.
    children: [notbounties.cleanEntities]
  notbounties.cleanentities:
    default: op
    description: Use the command /bounty cleanEntities (radius)
  notbounties.set:
    default: true
    description: Set bounties.
  notbounties.view:
    default: true
    description: View bounties and the bounty GUI.
  notbounties.stats:
    default: true
    description: View your player stats and the leaderboard.
  notbounties.buyown:
    default: true
    description: Buy your own bounty.
  notbounties.immune:
    default: false
    description: Immune to having bounties set on them.
  notbounties.buyimmunity:
    default: true
    description: Buy immunity.
  notbounties.removeimmunity:
    default: true
    description: Remove own immunity.
  notbounties.tracker:
    default: true
    description: Use a bounty tracker.
  # These tracker and poster perms override the settings in display.yml
  notbounties.spawntracker:
    default: false
    description: Spawn in a bounty tracker.
  notbounties.writeemptytracker:
    default: false
    description: Write a bounty into an empty tracker.
  notbounties.washtracker:
    default: false
    description: Wash a bounty tracker.
  notbounties.crafttracker:
    default: false
    description: Craft a bounty tracker.
  notbounties.postertracking:
    default: false
    description: Click on a poster with an empty tracker to track it.
  notbounties.spawnposter:
    default: false
    description: Spawn in a bounty poster.
  notbounties.washposter:
    default: false
    description: Wash a bounty poster.
  notbounties.craftposter:
    default: false
    description: Craft a bounty poster.
  notbounties.writeposter:
    default: false
    description: Write a bounty poster to an empty map.
  notbounties.whitelist:
    default: true
    description: Whitelist players to claim your bounty.
  notbounties.basic:
    default: true
    description: Use help, tutorial, and broadcast commands.
    children:
      notbounties.basic.tutorial: true
  notbounties.basic.tutorial:
    default: true
    description: Use the tutorial command.
  notbounties.removeset:
    default: false
    description: Remove bounties you set.
  notbounties.challenges:
    default: true
    description: View bounty challenges.
  notbounties.player:
    description: All the basic player permissions.
    children:
      - notbounties.set
      - notbounties.view
      - notbounties.buyown
      - notbounties.buyimmunity
      - notbounties.removeimmunity
      - notbounties.tracker
      - notbounties.whitelist
      - notbounties.basic
      - notbounties.challenges
      - notbounties.stats
  notbounties.immunity.murder:
    default: false
    description: Immune to murder auto-bounties.
  notbounties.immunity.random:
    default: false
    description: Immune to random auto-bounties.
  notbounties.immunity.timed:
    default: false
    description: Immune to timed auto-bounties.
  notbounties.hunt:
    default: true
    description: Allow players to use the bounty hunt feature.
    children:
      - notbounties.hunt.start
      - notbounties.hunt.participate
  notbounties.hunt.start:
    default: true
    description: Start a bounty hunt.
  notbounties.hunt.participate:
    default: true
    description: Join or leave a bounty hunt.
libraries:
  - com.mysql:mysql-connector-j:9.2.0
  - io.lettuce:lettuce-core:6.6.0.RELEASE