package me.jadenp.notbounties.features.settings.databases.proxy.driver;

import me.jadenp.notbounties.features.settings.databases.proxy.ProxyMessaging;

import java.sql.*;
import java.util.*;

class ProxyStatement implements Statement {
    private final ProxyConnection connection;
    private boolean closed = false;
    private int queryTimeout = 0;

    ProxyStatement(ProxyConnection connection) {
        this.connection = connection;
    }

    private void ensureOpen() throws SQLException {
        if (closed) throw new SQLException("Statement is closed");
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        ensureOpen();
        ProxyMessaging.DBResponse resp = ProxyMessaging.requestExecuteQuery(sql, Collections.emptyList(), 10_000);
        if (resp.rows == null || resp.columns == null) throw new SQLException("No result set returned");
        return ProxyResultSets.create(resp.rows, resp.columns);
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        ensureOpen();
        ProxyMessaging.DBResponse resp = ProxyMessaging.requestExecuteUpdate(sql, Collections.emptyList(), 10_000);
        return resp.updateCount;
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        ensureOpen();
        // We don't expect results for DDL in this project; treat as update
        executeUpdate(sql);
        return false;
    }

    @Override
    public void close() {
        closed = true;
    }

    @Override
    public int getMaxFieldSize() throws SQLException { return 0; }
    @Override
    public void setMaxFieldSize(int max) throws SQLException { }
    @Override
    public int getMaxRows() throws SQLException { return 0; }
    @Override
    public void setMaxRows(int max) throws SQLException { }
    @Override
    public void setEscapeProcessing(boolean enable) throws SQLException { }
    @Override
    public int getQueryTimeout() throws SQLException { return queryTimeout; }
    @Override
    public void setQueryTimeout(int seconds) throws SQLException { this.queryTimeout = seconds; }
    @Override
    public void cancel() throws SQLException { }
    @Override
    public SQLWarning getWarnings() throws SQLException { return null; }
    @Override
    public void clearWarnings() throws SQLException { }
    @Override
    public void setCursorName(String name) throws SQLException { }
    @Override
    public ResultSet getResultSet() throws SQLException { return null; }
    @Override
    public int getUpdateCount() throws SQLException { return -1; }
    @Override
    public boolean getMoreResults() throws SQLException { return false; }
    @Override
    public void setFetchDirection(int direction) throws SQLException { }
    @Override
    public int getFetchDirection() throws SQLException { return ResultSet.FETCH_FORWARD; }
    @Override
    public void setFetchSize(int rows) throws SQLException { }
    @Override
    public int getFetchSize() throws SQLException { return 0; }
    @Override
    public int getResultSetConcurrency() throws SQLException { return ResultSet.CONCUR_READ_ONLY; }
    @Override
    public int getResultSetType() throws SQLException { return ResultSet.TYPE_FORWARD_ONLY; }
    @Override
    public void addBatch(String sql) throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override
    public void clearBatch() throws SQLException { }
    @Override
    public int[] executeBatch() throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override
    public Connection getConnection() throws SQLException { return connection; }
    @Override
    public boolean getMoreResults(int current) throws SQLException { return false; }
    @Override
    public ResultSet getGeneratedKeys() throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException { return executeUpdate(sql); }
    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException { return executeUpdate(sql); }
    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException { return executeUpdate(sql); }
    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException { return execute(sql); }
    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException { return execute(sql); }
    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException { return execute(sql); }
    @Override
    public int getResultSetHoldability() throws SQLException { return ResultSet.HOLD_CURSORS_OVER_COMMIT; }
    @Override
    public boolean isClosed() throws SQLException { return closed; }
    @Override
    public void setPoolable(boolean poolable) throws SQLException { }
    @Override
    public boolean isPoolable() throws SQLException { return false; }
    @Override
    public void closeOnCompletion() throws SQLException { }
    @Override
    public boolean isCloseOnCompletion() throws SQLException { return false; }
    @Override
    public long getLargeUpdateCount() throws SQLException { return getUpdateCount(); }
    @Override
    public void setLargeMaxRows(long max) throws SQLException { }
    @Override
    public long getLargeMaxRows() throws SQLException { return 0; }
    @Override
    public long[] executeLargeBatch() throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override
    public long executeLargeUpdate(String sql) throws SQLException { return executeUpdate(sql); }
    @Override
    public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException { return executeUpdate(sql); }
    @Override
    public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException { return executeUpdate(sql); }
    @Override
    public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException { return executeUpdate(sql); }
    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException { throw new SQLException("Not a wrapper"); }
    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException { return false; }
}
